<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class OwnerUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'string',
            'fname' => 'string|required',
            'lname' => 'string|required',
            'other_name' => 'string|required',
            'address' => 'string|required',
            'telephone' => 'numeric',
            'email' => 'required|email|unique:owners'
        ];
    }


    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
